version: 2.1
orbs:
  ruby: circleci/ruby@1.8.0
  heroku: circleci/heroku@1.2.6

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.2-node
    working_directory: ~/crypto_app
    steps:
      - checkout:
          path: ~/crypto_app
      - ruby/install-deps

  test:
    docker:
      - image: cimg/ruby:3.1.2-node
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: crypto_app_test
          MYSQL_ROOT_USER: root
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/crypto_app
    steps:
      - checkout:
          path: ~/crypto_app
      - ruby/install-deps
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: yarn install
          command: yarn install
      - run: bundle exec bin/webpack
      - run:
          name: Rspec
          command: bundle exec rspec

  deploy:
    docker:
      - image: cimg/ruby:3.1.2-node
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - heroku/install
      - run:
          name: heroku login
          command: heroku container:login
      - run:
          name: push docker image
          command: heroku container:push web -a $HEROKU_APP_NAME
      - run:
          name: release docker image
          command: heroku container:release web -a $HEROKU_APP_NAME
      - run:
          name: webpacker compile
          command: bundle exec rails webpacker:compile
      - run:
          name: database setup
          command: heroku run bundle exec rake db:migrate RAILS_ENV=production -a $HEROKU_APP_NAME

workflows:
  version: 2
  build__test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main